#!/bin/bash
# Quick commands to setup admin superuser with immediate approval

echo "🔧 Superuser Setup Commands"
echo "======================================"
echo ""
echo "1️⃣  DELETE OLD SUPERUSERS"
echo "   Remove any existing superusers before creating new ones"
echo ""
echo "   Interactive (with confirmation):"
echo "   python manage.py delete_old_superusers"
echo ""
echo "   Non-interactive (automatic confirmation):"
echo "   python manage.py delete_old_superusers --confirm"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "2️⃣  CREATE APPROVED SUPERUSER"
echo "   Create new admin with immediate approval (no pending status)"
echo ""
echo "   Interactive (prompts for all details):"
echo "   python manage.py create_approved_superuser"
echo ""
echo "   With arguments (non-interactive):"
echo "   python manage.py create_approved_superuser \\"
echo "     --email admin@school.com \\"
echo "     --username admin \\"
echo "     --password YourSecurePassword123 \\"
echo "     --first-name Admin \\"
echo "     --last-name User"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ COMPLETE FRESH SETUP"
echo ""
echo "   cd /root/Omar-s-SMC/backend"
echo "   source venv/bin/activate"
echo "   python manage.py delete_old_superusers --confirm"
echo "   python manage.py create_approved_superuser \\"
echo "     --email admin@school.com \\"
echo "     --username admin \\"
echo "     --password SecurePass123 \\"
echo "     --first-name Admin \\"
echo "     --last-name User"
echo "   deactivate"
echo ""
echo "✅ Result: Admin can login immediately without approval delay!"
echo ""
