# Generated by Django 5.2.7 on 2025-10-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='target_classes',
            field=models.ManyToManyField(blank=True, related_name='target_notices', to='classes.class'),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_role',
            field=models.CharField(choices=[('all', 'All'), ('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='all', max_length=10),
        ),
    ]
