# Generated by Django 5.2.7 on 2025-10-08 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_attendancerecord_subject'),
        ('classes', '0001_initial'),
        ('users', '0002_student_address_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('max_score', models.FloatField(default=100)),
                ('date', models.DateField()),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='users.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.subject')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['student', 'subject', 'date'], name='academics_m_student_55c806_idx')],
            },
        ),
    ]
