# Generated by Django 5.2.7 on 2025-10-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
