# Generated by Django 5.2.7 on 2025-10-08 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_mark_published'),
        ('users', '0002_student_address_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='invigilator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilations', to='users.teacher'),
        ),
    ]
