# Generated by Django 5.2.7 on 2025-10-09 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_exam_invigilator'),
        ('classes', '0001_initial'),
        ('users', '0002_student_address_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject_assignments', to='classes.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='users.teacher')),
            ],
            options={
                'ordering': ['teacher', 'class_assigned', 'subject'],
                'unique_together': {('teacher', 'subject', 'class_assigned')},
            },
        ),
    ]
