# Generated by Django 5.2.7 on 2025-12-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_resultsubmission_mark_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
