# Generated by Django 5.2.7 on 2026-01-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_exam_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
