# Generated by Django 5.2.7 on 2026-01-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_exam_exam_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='fourth_subject_eligible',
            field=models.BooleanField(default=False, help_text='Can this subject be selected as a fourth subject?'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
