# Generated by Django 5.2.7 on 2026-01-31 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_exam_batch_and_mark_exam'),
        ('academics', '0011_subject_fourth_subject_eligible_alter_subject_code'),
    ]

    operations = [
    ]
