# Generated by Django 5.2.7 on 2026-01-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_merge_20260131_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at', 'date', 'start_time']},
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
