# Generated by Django 5.2.7 on 2026-01-31 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_alter_exam_options_remove_exam_batch_id_and_more'),
        ('classes', '0002_alter_class_unique_together_class_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classes.class'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_fourth_subject',
            field=models.BooleanField(default=False, help_text='Is this a fourth subject?'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='classes',
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('class_assigned', 'name')},
        ),
    ]
