# Generated by Django 5.2.7 on 2026-01-31 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_alter_subject_unique_together_subject_class_assigned_and_more'),
        ('classes', '0002_alter_class_unique_together_class_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='class_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classes.class'),
        ),
    ]
