# Generated by Django 5.2.7 on 2026-01-31 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0002_testimonial_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialrequest',
            name='note',
            field=models.TextField(blank=True, help_text='Student note for testimonial request', null=True),
        ),
        migrations.AddField(
            model_name='testimonialrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When admin approved/rejected', null=True),
        ),
        migrations.AddField(
            model_name='testimonialrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection by admin', null=True),
        ),
        migrations.AlterField(
            model_name='testimonialrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='TestimonialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bangla_name', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=50, null=True)),
                ('registration', models.CharField(blank=True, max_length=50, null=True)),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('father_bn', models.CharField(blank=True, max_length=200, null=True, verbose_name='Father Name (Bangla)')),
                ('mother_bn', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mother Name (Bangla)')),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('post_office', models.CharField(blank=True, max_length=100, null=True)),
                ('upazila', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('gpa', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, help_text='Year for testimonial', null=True)),
                ('serial_number', models.CharField(help_text='Unique serial number (min 5 digits)', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('testimonial_request', models.OneToOneField(help_text='Related testimonial request', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='transcripts.testimonialrequest')),
            ],
            options={
                'verbose_name': 'Testimonial Detail',
                'verbose_name_plural': 'Testimonial Details',
                'ordering': ['-created_at'],
            },
        ),
    ]
