# Generated by Django 5.2.7 on 2025-10-03 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fees", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="users.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fee",
            unique_together={("class_assigned", "month", "title")},
        ),
    ]
