# Generated by Django 5.2.7 on 2025-12-30 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_initial'),
        ('fees', '0002_payment_sslcommerz_fields'),
    ]

    operations = [
    ]
