# Generated by Django 5.2.7 on 2026-01-12 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_exam_exam_fee'),
        ('fees', '0003_merge_0002_initial_0002_payment_sslcommerz_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='academics.exam'),
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('exam', 'Exam')], default='regular', max_length=20),
        ),
    ]
