# Generated by Django 5.2.7 on 2026-01-31 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_alter_subject_unique_together_subject_class_assigned_and_more'),
        ('fees', '0005_fee_payment_intent'),
        ('users', '0010_student_name_bangla_student_post_office_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='users.student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='academics.exam'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paid', 'Paid'), ('complete', 'Complete')], default='pending', max_length=10),
        ),
    ]
