# Generated by Django 5.2.7 on 2025-10-03 13:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "link",
                    models.URLField(
                        blank=True, help_text="External link to material", null=True
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload file directly",
                        null=True,
                        upload_to="materials/",
                    ),
                ),
                (
                    "uploaded_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "class_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="classes.class",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Material",
                "verbose_name_plural": "Class Materials",
                "ordering": ["-uploaded_date"],
            },
        ),
    ]
