# Generated by Django 5.2.7 on 2025-10-08 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmaterial',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='academics.subject'),
        ),
    ]
