# Generated by Django 5.2.7 on 2025-10-09 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_classmaterial_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmaterial',
            name='file',
            field=models.FileField(blank=True, help_text='Upload file directly (deprecated)', null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='classmaterial',
            name='link',
            field=models.URLField(blank=True, help_text='External link to material (deprecated)', null=True),
        ),
        migrations.CreateModel(
            name='MaterialAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('file', 'File'), ('url', 'URL')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='material_attachments/')),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(help_text='Attachment title or filename', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='materials.classmaterial')),
            ],
            options={
                'verbose_name': 'Material Attachment',
                'verbose_name_plural': 'Material Attachments',
                'ordering': ['created_at'],
            },
        ),
    ]
