# Generated by Django 5.2.7 on 2025-10-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_student_address_student_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="date_of_birth",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="designation",
            field=models.CharField(
                blank=True, default="Teacher", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="index_num",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Index Number",
            ),
        ),
    ]
