# Generated by Django 5.2.7 on 2025-10-22 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teacher_date_of_birth_teacher_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='index_num',
        ),
    ]
