# Generated by Django 5.2.7 on 2025-10-24 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_teachersubjectassignment'),
        ('classes', '0001_initial'),
        ('users', '0004_remove_teacher_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='preferred_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_teachers', to='classes.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='preferred_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_teachers', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Teacher ID'),
        ),
    ]
