# Generated by Django 5.2.7 on 2025-12-30 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_password_reset_otp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='users_passw_user_id_8dd2f7_idx',
            old_name='users_passw_user_id_f8c700_idx',
        ),
    ]
