# Generated by Django 5.2.7 on 2025-12-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_users_passw_user_id_f8c700_idx_users_passw_user_id_8dd2f7_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
