# Generated by Django 5.2.7 on 2026-01-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_student_birth_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name_bangla',
            field=models.CharField(blank=True, help_text='Student name in Bengali', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='post_office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_id',
            field=models.CharField(blank=True, help_text='College registration ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(blank=True, help_text='e.g., 2022-2023', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
