# Generated by Django 5.2.7 on 2026-01-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_student_name_bangla_student_post_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hsc_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='HSC GPA', max_digits=4, null=True),
        ),
    ]
