# Generated by Django 5.2.7 on 2026-01-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_student_hsc_gpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hsc_gpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name_bangla',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registration_id',
        ),
        migrations.AddField(
            model_name='student',
            name='bangla_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name in Bangla'),
        ),
        migrations.AddField(
            model_name='student',
            name='registration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='post_office',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Post Office'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Academic Session'),
        ),
        migrations.AlterField(
            model_name='student',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Village'),
        ),
    ]
